version: "3.8"

services:
  client:
    container_name: bu-client-c
    build:
      context: .
      target: clientBU
    volumes:
      - ./src:/src
      - ./node_modules
    ports:
      - 3000:3000