version: '3.8'

services:
  server:
    container_name: bu-server-c
    build:
      context: .
      target: serverBU
    volumes:
      - ./server-buApp
      - ./server-buApp/JS:/server-buApp/JS
      - ./server-buApp/node_modules
    ports:
      - 5000:5000
